# Generated by Django 5.0.6 on 2024-07-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_body_post_content_remove_post_title_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
    ]
