# Generated by Django 5.0.7 on 2024-08-10 19:14

from django.db import migrations


def create_slugs(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    for post in Post.objects.all():
        if not post.slug:
            post.slug = post.author.username + '-' + str(post.created_at)
            post.save()


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0010_post_slug'),
    ]

    operations = [
        migrations.RunPython(create_slugs),
    ]
