# Generated by Django 5.0.7 on 2024-08-10 19:21
import random
import string

from django.db import migrations
from django.utils.text import slugify


def create_post_slug(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    for post in Post.objects.all():
        post.slug = slugify(post.content[:50]) + '-' + post.created_at.strftime('%Y-%m-%d')
        while Post.objects.filter(slug=post.slug).exists():
            post.slug = post.slug + '-' + ''.join(random.choice(string.ascii_lowercase) for _ in range(5))


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_slug'),
    ]

    operations = [
        migrations.RunPython(create_post_slug)
    ]
