# Generated by Django 5.0.7 on 2024-08-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackListedToken',
        ),
    ]
