# Generated by Django 5.0.7 on 2024-08-16 10:25
from django.contrib.auth.models import User
from django.db import migrations

from ..models import Profile, CustomUser


def migrate_to_custom_user(apps, schema_editor):
    for profile in Profile.objects.all():
        user = User.objects.get(id=profile.user)
        custom_user = CustomUser(
            username=user.username,
            email=user.email,
            first_name=user.first_name,
            last_name=user.last_name,
            bio=profile.bio,
            birth_date=profile.birth_date,
            profile_pic=profile.profile_pic,
            is_staff=user.is_staff,
            is_active=user.is_active
        )
        custom_user.set_password(user.password)
        custom_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_blacklistedtoken'),
    ]

    operations = [
        migrations.RunPython(migrate_to_custom_user)
    ]
